# Autogenerated by nbdev

d = { 'settings': { 'branch': '',
                'doc_baseurl': '/notebook',
                'doc_host': 'https://.github.io',
                'git_url': 'https://github.com//notebook',
                'lib_path': 'notebook'},
  'syms': {'notebook.core': {'notebook.core.foo': ('core.html#foo', 'notebook/core.py')}}}
